name: ML-projects
channels:
  - defaults
dependencies:
  - ca-certificates=2018.03.07=0
  - cycler=0.10.0=py34_0
  - intel-openmp=2018.0.3=0
  - matplotlib=2.0.0=np111py34_0
  - numpy=1.11.3=py34_0
  - pandas=0.19.2=np111py34_1
  - pip=9.0.1=py34_1
  - pyparsing=2.2.0=py34_0
  - pyqt=5.6.0=py34_2
  - python=3.4.5=0
  - python-dateutil=2.6.1=py34_0
  - pytz=2017.2=py34_0
  - scikit-learn=0.18.1=np111py34_1
  - scipy=0.18.1=np111py34_1
  - seaborn=0.7.1=py34_0
  - setuptools=27.2.0=py34_0
  - sip=4.18=py34_0
  - six=1.10.0=py34_0
  - toolz=0.8.2=py34_0
  - wheel=0.29.0=py34_0
  - Jupyter
